### PR TITLE
Vertically-center Option contents

### PR DESCRIPTION
**Pull request by openjck**

### CODE REVIEW

**Comment by hamilton** [comment]
Did this get checked in storybook? This PR creates an issue where the checkbox is not aligned with the starting element.

Screen Shot 2020-05-27 at 6 14 52 PM

**Comment by hamilton** [comment]
One approach would be to have the alignment be set to `center` only if there is no description.

**Comment by openjck** [comment]
For sure. I definitely checked it in Storybook. 😃

To be fair, I would say that the checkbox is not start-aligned, but it it is center-aligned. I was happy with the way this looked, but if you want, we could have it start-align if there is a description.

**Comment by hamilton** [comment]
my bad :) different taste. Thanks for taking another look. I'm noticing in the `SideBySide` example, the font `OptionMenu` has no description, but I would expect these elements to all be vertically centered. Is that intended?

Screen Shot 2020-05-28 at 6 20 14 PM

**Comment by openjck** [comment]
I'm sorry, but I'm not sure I understand. Can you be more specific?

If you mean that the icons don't appear to be vertically-aligned, I have to say that it seems like a font issue that I don't quite understand. It doesn't happen with things like color swatches. Changing the font to a sans-serif font in *SideBySideStory.svelte*, which I did, fixes the vertical alignment. Alternatively, a relative position could be applied like it is to the *I* icon.

**Pull request merged**
