### PR TITLE
Add icons

### PR DESCRIPTION
**Pull request by hamilton**

### CODE REVIEW

**Comment by openjck** [comment]
Do we need the empty *packages/icons/style.css* file?

**Comment by openjck** [comment]
Maybe it doesn't make sense to address the ESLint issues right now. Migrating components is error-prone enough. I wouldn't mind getting that working first and then going in with a surgical knife to fix code quality issues later.

**Comment by openjck** [comment]
This does increase the ESLint problem count, but after thinking about it and porting the OptionMenu component, I think it may be best to address those later. Porting components is error-prone enough. I'd rather use a surgical knife to deal with code quality issues later once we know that everything works.

**Comment by hamilton** [comment]
Thanks for the review. It turns out I hadn't run `npm install` since the last bits were configured – thanks for catching those eslint errors. This said, (1) CI should be doing the job of alerting of eslint errors here, not human reviewers.

**Comment by openjck** [comment]
> This said CI should be doing the job of alerting of eslint errors here, not human reviewers.

Yeah, I'm down for that. The only thing is that CI would be failing for the foreseeable future since we have a lot of current ESLint errors.

**Pull request merged**
